---
- hosts: nginx
  tasks:
    - name: Run the equivalent of apt-get update.
      become: true
      apt: 
        update_cache: yes

    - name: Install package "nginx"
      become: true
      apt: name={{item}} state=latest
      with_items:
          - nginx
    
    - name: Start nginx
      become: true
      service:
        name: nginx
        state: started
